In [2]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("C://kaoutar//DataWerhouse//Projet//linkedin_jobs_20260318_0312.csv")
data.head()

,title,company,location,date_posted,job_url,search_keyword,scraped_at
0,Data Scientist (H/F),Orange Maroc,"Casablanca-Settat, Maroc",2026-03-17,https://ma.linkedin.com/jobs/view/data-scienti...,Data Scientist,2026-03-18T02:30:52.381834
1,Data Scientist / IA / ML,Capgemini,"Casablanca, Casablanca-Settat, Maroc",2026-03-13,https://ma.linkedin.com/jobs/view/data-scienti...,Data Scientist,2026-03-18T02:30:52.382837
2,AI & Data Scientist,Capgemini Engineering,"Casablanca, Casablanca-Settat, Maroc",2026-03-13,https://ma.linkedin.com/jobs/view/ai-data-scie...,Data Scientist,2026-03-18T02:30:52.382837
3,R&D Engineer,ALTEN MAROC,"Fès, Fès-Meknès, Maroc",2026-03-13,https://ma.linkedin.com/jobs/view/r-d-engineer...,Data Scientist,2026-03-18T02:30:52.383835
4,Data Scientist Senior,Astek,Casablanca et périphérie,2026-03-11,https://ma.linkedin.com/jobs/view/data-scienti...,Data Scientist,2026-03-18T02:30:52.383835

In [4]:
data.describe()

,title,company,location,date_posted,job_url,search_keyword,scraped_at
count,570,570,570,570,570,570,570
unique,469,207,36,8,531,43,304
top,Expert technique en tests automatisés,Inetum,"Casablanca, Casablanca-Settat, Maroc",2026-03-13,https://ma.linkedin.com/jobs/view/c%2B%2B-deve...,Data Scientist,2026-03-18T02:37:31.932031
freq,14,36,136,128,2,79,9

In [2]:
data.shape()

NameError: name 'data' is not defined